# Generated by Django 4.1.2 on 2022-10-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='album',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
